// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniPdm.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniPdm.Storage.Migrations
{
    [DbContext(typeof(PdmDbContext))]
    partial class PdmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniPdm.Domain.Composition.BomLink", b =>
                {
                    b.Property<Guid>("ParentVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildObjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ParentVersionId", "ChildObjectId");

                    b.HasIndex("ChildObjectId");

                    b.ToTable("bom_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_bom_links_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("MiniPdm.Domain.Objects.PdmObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Designation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StandardName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Designation")
                        .IsUnique()
                        .HasFilter("\"Type\" IN (1, 2) AND \"Designation\" IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("\"Type\" = 3 AND \"NormalizedName\" IS NOT NULL");

                    b.HasIndex("CurrentVersionId", "Id");

                    b.ToTable("pdm_objects", null, t =>
                        {
                            t.HasCheckConstraint("ck_pdm_objects_identity", "(\"Type\" IN (1,2) AND \"Designation\" IS NOT NULL AND \"NormalizedName\" IS NULL) OR (\"Type\" = 3 AND \"Designation\" IS NULL AND \"NormalizedName\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MiniPdm.Domain.Versions.ObjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Mass")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Material")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId", "Version")
                        .IsUnique();

                    b.ToTable("object_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_object_versions_mass_nonnegative", "\"Mass\" IS NULL OR \"Mass\" >= 0");

                            t.HasCheckConstraint("ck_object_versions_state", "\"State\" IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_object_versions_version_positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("MiniPdm.Storage.Entities.BackgroundTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("LastResult")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("background_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_background_tasks_interval", "\"IntervalMinutes\" BETWEEN 1 AND 525600");

                            t.HasCheckConstraint("ck_background_tasks_state", "\"State\" IN ('Idle', 'Running', 'Succeeded', 'PartiallySucceeded', 'Failed', 'Interrupted')");
                        });
                });

            modelBuilder.Entity("MiniPdm.Storage.Entities.ImportJournal", b =>
                {
                    b.Property<Guid>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImportId");

                    b.ToTable("import_journal", (string)null);
                });

            modelBuilder.Entity("MiniPdm.Domain.Composition.BomLink", b =>
                {
                    b.HasOne("MiniPdm.Domain.Objects.PdmObject", "ChildObject")
                        .WithMany()
                        .HasForeignKey("ChildObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniPdm.Domain.Versions.ObjectVersion", "ParentVersion")
                        .WithMany("Components")
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildObject");

                    b.Navigation("ParentVersion");
                });

            modelBuilder.Entity("MiniPdm.Domain.Objects.PdmObject", b =>
                {
                    b.HasOne("MiniPdm.Domain.Versions.ObjectVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId", "Id")
                        .HasPrincipalKey("Id", "ObjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("MiniPdm.Domain.Versions.ObjectVersion", b =>
                {
                    b.HasOne("MiniPdm.Domain.Objects.PdmObject", "Object")
                        .WithMany("Versions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Object");
                });

            modelBuilder.Entity("MiniPdm.Domain.Objects.PdmObject", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MiniPdm.Domain.Versions.ObjectVersion", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
